// Unified storage service — uses electron-store via IPC in Electron, localStorage in browser.

const isElectron = Boolean(window.electronAPI);

async function get(key) {
  if (isElectron) return window.electronAPI.storeGet(key);
  const raw = localStorage.getItem(key);
  return raw ? JSON.parse(raw) : null;
}

async function set(key, value) {
  if (isElectron) return window.electronAPI.storeSet(key, value);
  localStorage.setItem(key, JSON.stringify(value));
}

async function del(key) {
  if (isElectron) return window.electronAPI.storeDelete(key);
  localStorage.removeItem(key);
}

// Vocab stats
export async function getVocabStats() {
  return (await get('vocabStats')) || {};
}

export async function updateVocabStats(wordId, correct) {
  const stats = await getVocabStats();
  if (!stats[wordId]) stats[wordId] = { times_tested: 0, times_correct: 0 };
  stats[wordId].times_tested += 1;
  if (correct) stats[wordId].times_correct += 1;
  await set('vocabStats', stats);
}

export async function resetVocabStats() {
  await del('vocabStats');
}

// Wrong answers (review notebook)
export async function getWrongAnswers() {
  return (await get('wrongAnswers')) || [];
}

export async function addWrongAnswer(entry) {
  const list = await getWrongAnswers();
  // Avoid exact duplicate questions in the list
  const exists = list.some(
    w => w.question === entry.question && w.quizType === entry.quizType
  );
  if (!exists) list.push({ ...entry, addedAt: Date.now() });
  // Keep last 200 wrong answers
  const trimmed = list.slice(-200);
  await set('wrongAnswers', trimmed);
}

export async function removeWrongAnswer(index) {
  const list = await getWrongAnswers();
  list.splice(index, 1);
  await set('wrongAnswers', list);
}

export async function clearWrongAnswers() {
  await del('wrongAnswers');
}

// Quiz history (last 50 sessions)
export async function getQuizHistory() {
  return (await get('quizHistory')) || [];
}

export async function addQuizSession(session) {
  const history = await getQuizHistory();
  history.push({ ...session, completedAt: Date.now() });
  const trimmed = history.slice(-50);
  await set('quizHistory', trimmed);
}

// Extended vocab bank (words generated by LLM beyond the base JSON)
// Each entry gets a stable string ID like 'gen_1', 'gen_2' …
export async function getExtendedVocab() {
  return (await get('extendedVocab')) || [];
}

export async function appendExtendedVocab(newWords) {
  const existing = await getExtendedVocab();
  const existingSet = new Set(existing.map(w => w.word.toLowerCase()));
  const base = existing.length;
  const fresh = newWords
    .filter(w => w.word && !existingSet.has(w.word.toLowerCase()))
    .map((w, i) => ({ ...w, id: `gen_${base + i + 1}` }));
  const merged = [...existing, ...fresh];
  await set('extendedVocab', merged);
  return merged;
}

export async function clearExtendedVocab() {
  await del('extendedVocab');
}

// API Settings — persisted so users don't re-enter after restart
export async function getSettings() {
  return (await get('apiSettings')) || {};
}

export async function saveSettings(settings) {
  await set('apiSettings', settings);
}

export async function hasApiKey() {
  const s = await getSettings();
  return Boolean(s.apiKey && s.apiKey.trim().length > 0);
}
